### ISSUE TITLE
404 Client Error

### ISSUE THREAD

**Issue by chadsaun** [philipbl/LCR-API#6]
Just trying to get the member list `member_list = lcr.member_list()` and am getting the below error. Is the service just temporarily down?

```
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://lcr.churchofjesuschrist.org/services/report/member-list?lang=eng&unitNumber=1234567
```

**Comment by philipbl** [comment]
Unfortunately, I don’t have access to LCR anymore to test it out. It would be great if you could debug the problem. 

One issue that I see in the URL is that the unit number doesn’t look valid.

**Comment by chadsaun** [comment]
I replaced my unit number on purpose.

I just tested it again and it's still getting a 404. Does the church have any documentation anywhere about this service?

**Comment by chadsaun** [comment]
FYI - I've stopped using `member_list()` and switched to using `members_alt()` 😕

**Comment by philipbl** [comment]
Is `members_alt()` working for you? It looks like that should become the new `member_list()`.

**Comment by chadsaun** [comment]
Yes, `members_alt()` is still working, and if `member_list()` continues to not work then it should be replaced with `members_alt()`.

I wish I could find any information on the source of this API. If there were any kind of documentation about it.

**Comment by ephraimkunz** [comment]
No documentation about these apis exists publicly, because they're not meant for external developers. 

I discovered the changed member list url by inspecting the http traffic while trying to access the member list via the web ui.

**Comment by chadsaun** [comment]
Ah I see, ok 👍
